version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: example-laravel
    container_name: example-laravel
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3309
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=password
    ports:
      - "8888:80"

    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: my-laravel-db
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

    volumes:
      - .docker/mysql-data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my-phpmyadmin
    restart: unless-stopped
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=password
    ports:
      - "8889:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
